// <auto-generated />
namespace Rieltor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class counterdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(counterdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201611121515375_counterdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
